# Generated by Django 4.2.2 on 2023-06-24 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_supplier_purchase'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
